### PR TITLE
Added ANSI/VT banners

### PR DESCRIPTION
**Pull request by PhMajerus**
Added ANSI/VT banners for the Windows console and the Windows Terminal, for 80 and 120 columns.

These 4 text+VT inband control files display the Build 2020 banner in the Windows console and Windows Terminal, formatted for 80 columns or 120 columns.
OEM/ANSI .ans versions can be used in cmd.exe with the `type` command (preceded by `chcp 437` if needed) and UTF-8 .utf8 versions can be used with PowerShell with `Get-Content filename.utf8 -Encoding UTF8` or WSL using the `cat` command.

image

Files can also be used directly from GitHub:
`curl https://raw.githubusercontent.com/PhMajerus/Build2020_DigitalSwag/master/Console%20%26%20Windows%20Terminal%20ANSIs%20-%20Build%202020/Build2020_WinTerm_120.utf8`
`curl https://raw.githubusercontent.com/PhMajerus/Build2020_DigitalSwag/master/Console%20%26%20Windows%20Terminal%20ANSIs%20-%20Build%202020/Build2020_WinTerm_80.utf8`

### CODE REVIEW

**Comment by isaacrlevin** [comment]
Can you update the filename with some unique name. We want to make sure you get credit for it

**Comment by PhMajerus** [comment]
@isaacrlevin 
The banners include a dim "PHM.lu" mark as author watermark as is common in ANSI-art files. I updated the folder and files names to better match the naming found in existing folders and to include "_PHM" token as author flag as well, don't really need more credit since it's mostly based on the assets already designed by Microsoft.
Hope this meets your requirements, feel free to fix, change, adapt or anything.

**Comment by isaacrlevin** [comment]
@PhMajerus looks good, are you done updating? If so, I will merge

**Comment by PhMajerus** [comment]
@isaacrlevin Yeah, I changed the 4 files before posting the update message. I don't have anything more right now except if users like it and start asking different sizes or ANSI-art logos.
Thanks :)

**Pull request merged**
